CREATE DATABASE IF NOT EXISTS development;
CREATE DATABASE IF NOT EXISTS test;
CREATE DATABASE IF NOT EXISTS production;

GRANT ALL PRIVILEGES ON *.* TO root@'%' IDENTIFIED BY 'root';

FLUSH PRIVILEGES;